### ISSUE TITLE
Nothing being generated at the end of a test run

### ISSUE THREAD

**Issue by jordan-romeroporter-earnin** [TitouanVanBelle/fastlane-plugin-xchtmlreport#3]
I've searched the directory and there's nothing being outputted by this plugin at all ... what gives?

**Comment by jordan-romeroporter-earnin** [comment]
Here's what I'm running:

``` lane :run_uitests do |values|
   scan(scheme:SCHEME, 
        only_testing: values[:only_testing],
        include_simulator_logs: false, 
        result_bundle:true)
   xchtmlreport
  end
```

**Comment by jordan-romeroporter-earnin** [comment]
One thing I've noticed in the scan logs, is that if the tests fail, then the xchtmlreport doesn't get called...? why does this happen and how do I resolve?

**Comment by yashwanth-l** [comment]
I see the same behavior as what @jordan-romeroporter-earnin mentioned above. Can anybody confirm?

**Comment by miguelgazela** [comment]
I'm seeing the same behaviour as well. If the build succeeds, it generates the html, but if the build fails the plugin is never executed. Did you guys figure it out? @jordan-romeroporter-earnin @yashwanth-l

**Comment by normand1** [comment]
Yeah, I'm seeing the same thing. If the tests fail then this plugin will not be executed:

```
+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | scan             | 105         |
| 💥   | scan             | 1214        |
+------+------------------+-------------+

DEBUG [2020-01-24 11:36:54.30]: All plugins are up to date
ERROR [2020-01-24 11:36:54.30]: fastlane finished with errors
DEBUG [2020-01-24 11:36:54.30]: All plugins are up to date
/Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/interface.rb:172:in `test_failure!': [!] Test execution failed. Exit status: 65 (FastlaneCore::Interface::FastlaneTestFailure)
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/scan/lib/scan/runner.rb:116:in `handle_results'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/scan/lib/scan/runner.rb:22:in `run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/scan/lib/scan/manager.rb:23:in `work'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/actions/run_tests.rb:16:in `run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:132:in `block in parsing_binding'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/bin/fastlane:23:in `load'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/bin/fastlane:23:in `<main>'
/Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/interface.rb:172:in `test_failure!': Test execution failed. Exit status: 65 (FastlaneCore::Interface::FastlaneTestFailure)
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/scan/lib/scan/runner.rb:116:in `handle_results'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/scan/lib/scan/runner.rb:22:in `run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/scan/lib/scan/manager.rb:23:in `work'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/actions/run_tests.rb:16:in `run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:132:in `block in parsing_binding'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/bin/fastlane:23:in `load'
	from /Users/Shared/Jenkins/.rvm/gems/ruby-2.6.1/bin/fastlane:23:in `<main>'
```

**Comment by glyuck** [comment]
Wrap you code in `begin / ensure` block:
```
begin
   scan(scheme:SCHEME, 
        only_testing: values[:only_testing],
        include_simulator_logs: false, 
        result_bundle:true)
ensure
   xchtmlreport
end
```
This way your lane will fail if tests don't pass (as expected) but `xchtmlreport` will be called anyway.

**Comment by yashwanth-l** [comment]
did this solution work for anyone?

**Comment by Mikuu** [comment]
the same behavior here, no index.html in case of failures

**Comment by yashwanth-l** [comment]
@glyuck I don't see it working, even if under a block. Can you please point to a working reference, if possible?

**Comment by yashwanth-l** [comment]
Any luck on this issue?

**Comment by Cheeezcake** [comment]
```ruby
  begin
    scan(disable_xcpretty: true,
         devices: simulators,
         scheme: options[:scheme],
         reset_simulator: true,
         prelaunch_simulator: true,
         result_bundle: true,
         fail_build: false)
  rescue
    UI.error "Some tests were failed :("
  end
       
  xchtmlreport(enable_junit: true)
  ```
